// In-memory store for label extraction result when navigating from scan-label back to add-wine.
// Cleared after add-wine consumes it.

export interface WineAttributes {
  oak: "oaked" | "unoaked" | "stainless" | null;
  oak_intensity: "new" | "neutral" | null;
  climate: "cool" | "moderate" | "warm" | null;
  body_inferred: "light" | "medium" | "full" | null;
  tannin_inferred: "low" | "medium" | "high" | null;
  acidity_inferred: "low" | "medium" | "high" | null;
  style: "conventional" | "natural" | "biodynamic" | "organic" | null;
}

export interface WineExtraction {
  producer: string | null;
  varietal: string | null;
  vintage: number | null;
  region: string | null;
  ai_summary: string | null;
  label_photo_url: string | null;
  /** Polished display image generated by AI (generate-bottle-image); falls back to label_photo_url */
  display_photo_url: string | null;
  image_confidence_score: number | null;
  image_generation_status: "generated" | "fallback_raw" | "failed" | null;
  image_generation_metadata: Record<string, unknown> | null;
  color: "red" | "white" | "skin-contact" | null;
  is_sparkling: boolean | null;
  ai_geography: string | null;
  ai_production: string | null;
  ai_tasting_notes: string | null;
  ai_pairings: string | null;
  drink_from: number | null;
  drink_until: number | null;
  wine_attributes: WineAttributes | null;
}

let last: WineExtraction | null = null;

export function setLastLabelExtraction(extraction: WineExtraction | null): void {
  last = extraction;
}

export function takeLastLabelExtraction(): WineExtraction | null {
  const v = last;
  last = null;
  return v;
}
